org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
android.useAndroidX=true
android.nonTransitiveRClass=true
android.nonFinalResIds=true
android.defaults.buildfeatures.resvalues=false
android.defaults.buildfeatures.shaders=false
harbor.versionCode=1
harbor.versionName=0.1.0-alpha01
